//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetrolPump.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PetrolPumpDbEntities : DbContext
    {
        public PetrolPumpDbEntities()
            : base("name=PetrolPumpDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Company> tbl_Company { get; set; }
        public virtual DbSet<tbl_Customer> tbl_Customer { get; set; }
        public virtual DbSet<tbl_Employee> tbl_Employee { get; set; }
        public virtual DbSet<tbl_EmployeeSalary> tbl_EmployeeSalary { get; set; }
        public virtual DbSet<tbl_Expense> tbl_Expense { get; set; }
        public virtual DbSet<tbl_FuelType> tbl_FuelType { get; set; }
        public virtual DbSet<tbl_Page> tbl_Page { get; set; }
        public virtual DbSet<tbl_Permission> tbl_Permission { get; set; }
        public virtual DbSet<tbl_Pump> tbl_Pump { get; set; }
        public virtual DbSet<tbl_PumpFuelType> tbl_PumpFuelType { get; set; }
        public virtual DbSet<tbl_Role> tbl_Role { get; set; }
        public virtual DbSet<tbl_Sensor> tbl_Sensor { get; set; }
        public virtual DbSet<tbl_Stock> tbl_Stock { get; set; }
        public virtual DbSet<tbl_Supplier> tbl_Supplier { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
    }
}
