//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetrolPump.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Stock
    {
        public int StockID { get; set; }
        public string OrderType { get; set; }
        public Nullable<int> SensorID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<bool> IsPurchased { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<bool> IsSaled { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
    
        public virtual tbl_Customer tbl_Customer { get; set; }
        public virtual tbl_Sensor tbl_Sensor { get; set; }
        public virtual tbl_Supplier tbl_Supplier { get; set; }
    }
}
