//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetrolPump.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Permission
    {
        public int PermissionID { get; set; }
        public int RoleID { get; set; }
        public int PageID { get; set; }
        public Nullable<bool> Can_View { get; set; }
        public Nullable<bool> Can_Add { get; set; }
        public Nullable<bool> Can_Update { get; set; }
        public Nullable<bool> Can_Delete { get; set; }
    
        public virtual tbl_Page tbl_Page { get; set; }
        public virtual tbl_Role tbl_Role { get; set; }
    }
}
