//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetrolPump.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Sensor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Sensor()
        {
            this.tbl_Stock = new HashSet<tbl_Stock>();
        }
    
        public int SensorID { get; set; }
        public int PumpID { get; set; }
        public Nullable<int> FuelTypeID { get; set; }
        public string SensorMAC { get; set; }
        public string TankTitle { get; set; }
        public Nullable<int> TankCapacity { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> FuelPresents { get; set; }
    
        public virtual tbl_FuelType tbl_FuelType { get; set; }
        public virtual tbl_Pump tbl_Pump { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stock> tbl_Stock { get; set; }
    }
}
